### ISSUE TITLE
Error when running the example code

### ISSUE THREAD

**Issue by jlindsey15** [lucidrains/byol-pytorch#15]
Hi!  When I try to run the Pytorch lightning example code, I get the following error.  Any idea how to fix this?  

Traceback (most recent call last):
  File "train.py", line 94, in <module>
    trainer.fit(model, train_loader)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line903, in fit
    mp.spawn(self.ddp_train, nprocs=self.num_processes, args=(model, ))
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGSEGV

**Comment by lucidrains** [comment]
hmm I'm not too sure actually, does it work if you restrict it to 1 gpu? `CUDA_VISIBLE_DEVICES=0 python train.py`?

**Comment by jlindsey15** [comment]
Trying with one GPU gives me a different error:

Traceback (most recent call last):
  File "train.py", line 94, in <module>
    trainer.fit(model, train_loader)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line918, in fit
    self.single_gpu_train(model)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 176, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line1093, in run_pretrain_routine
    self.train()
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 335, in train
    self.reset_train_dataloader(model)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py",line 199, in reset_train_dataloader
    if not _has_len(self.train_dataloader):
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py",line 50, in _has_len
    raise ValueError('`Dataloader` returned 0 length.'
ValueError: `Dataloader` returned 0 length. Please make sure that your Dataloader at least returns 1batch

**Comment by lucidrains** [comment]
@jlindsey15 ok, i think i know why. https://github.com/lucidrains/byol-pytorch/commit/e3c245311bcfee58982d1a63e66587f9b302ba31 can you try again?

**Comment by jlindsey15** [comment]
Thanks!  That fixed the second problem.  I now get a new error -- see below -- running on one GPU (and still get the original error running on multiple GPUs)

Traceback (most recent call last):
  File "train.py", line 102, in <module>
    trainer.fit(model, train_loader)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line918, in fit
    self.single_gpu_train(model)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 176, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line1093, in run_pretrain_routine
    self.train()
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 375, in train
    self.run_training_epoch()
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 445, in run_training_epoch
    enumerate(_with_is_last(train_dataloader)), "get_train_batch"
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/profiler/profilers.py", line 64, in profile_iterable
    value = next(iterator)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 843, in _with_is_last
    last = next(it)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47,in fetch
    return self.collate_fn(data)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 256] at entry 0 and [1, 256, 256] at entry 3

**Comment by lucidrains** [comment]
@jlindsey15 ahh, I believe you must have some greyscale images (mixed in with colored images) in your folder

**Comment by lucidrains** [comment]
@jlindsey15 ok, try again, this should fix the greyscale image problem, but it's probably better that you make sure it isn't auto-including some image you don't want pretraining on https://github.com/lucidrains/byol-pytorch/commit/87232dc89bd6b51fdf24d5174c20f806bad5b98e

**Comment by jlindsey15** [comment]
Thanks a lot for being so responsive, that fixed the issue and I am now able to train on one GPU.  I still get errors (now a different error) with multiple GPUs (see below).  Any ideas?  Also, do you have any idea why the grayscale / color issue might have come about?  I have used this same ImageNet copy with the standard Pytorch training code (https://github.com/pytorch/examples/blob/master/imagenet/main.py) and with the MOCO code (https://github.com/facebookresearch/moco) with no issues.  Could it be because the channel-wise normalization is not applied in the Dataloader in this code?

Multi-gpu error:

Traceback (most recent call last):
  File "train.py", line 103, in <module>
    trainer.fit(model, train_loader)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line903, in fit
    mp.spawn(self.ddp_train, nprocs=self.num_processes, args=(model, ))
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/share/apps/anaconda3-2019.03/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/share/apps/anaconda3-2019.03/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/share/apps/anaconda3-2019.03/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/share/apps/anaconda3-2019.03/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/share/apps/anaconda3-2019.03/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/share/apps/anaconda3-2019.03/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ImagesDataset.__init__.<locals>.<lambda>'

**Comment by lucidrains** [comment]
https://github.com/lucidrains/byol-pytorch/commit/6b6a167b4f154861c55bc8a06ede5c71e46c6e0e ok, put in another fix lol

**Comment by jlindsey15** [comment]
Thanks, just figured out the same fix.  I'm sorry to keep bothering you, but unfortunately all this has brought me back to the original error:


Traceback (most recent call last):
  File "train.py", line 104, in <module>
    trainer.fit(model, train_loader)
  File "/home/jwl2182/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line903, in fit
    mp.spawn(self.ddp_train, nprocs=self.num_processes, args=(model, ))
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/jwl2182/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGSEGV

**Comment by lucidrains** [comment]
@jlindsey15 yea, i'm not sure about that one

doing a quick google brings me to https://github.com/pytorch/fairseq/issues/1608

**Comment by lucidrains** [comment]
do you want to give the accepted solution on that page a try?
